### ISSUE TITLE
Parsing error loading recipe deeperdarker:sculk_affinity

### ISSUE THREAD

**Issue by ckaron0912** [KyaniteMods/DeeperAndDarker#123]
**Mod Version**: 1.1.6-forge

**Mod Loader**: forge

**Description**:
This is the same issue as #111. It seems like the typo wasn't the cause of this issue.

The server logs show the following error on startup:

```
[20:25:14] [main/ERROR] [minecraft/RecipeManager]: Parsing error loading recipe deeperdarker:sculk_affinity
com.google.gson.JsonSyntaxException: Invalid or unsupported recipe type 'jeed:effect_provider'
        at net.minecraft.world.item.crafting.RecipeManager.m_220253_(RecipeManager.java:170) ~[server-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:farmersdelight.mixins.json:accessor.RecipeManagerAccess
or,pl:mixin:A}
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?] {re:mixin}
        at net.minecraft.world.item.crafting.RecipeManager.fromJson(RecipeManager.java:169) ~[server-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:farmersdelight.mixins.json:accessor.RecipeManagerAccesso
r,pl:mixin:A}
        at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:67) ~[server-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:farmersdelight.mixins.json:accessor.RecipeManagerAccessor,
pl:mixin:A}
        at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:34) ~[server-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:farmersdelight.mixins.json:accessor.RecipeManagerAccessor,
pl:mixin:A}
        at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[server-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,re:mixin}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[server-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading}
        at net.minecraft.Util.m_214652_(Util.java:781) ~[server-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading}
        at net.minecraft.Util.m_214679_(Util.java:770) ~[server-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.2-43.2.1.jar%2367!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
```

**To Reproduce**:
1. Load up a minecraft forge server v1.19.2
2. Check the logs
3. See error

**Screenshots**:

![image](https://user-images.githubusercontent.com/9004735/209736029-0ca6413c-7bb3-470b-a548-930d0235de7d.png)
![image](https://user-images.githubusercontent.com/9004735/209736108-9e406b36-b5ae-4db1-aeec-a66e2eb69dd0.png)

**Additional context**:
Is "jeed:effect_provider" the right recipe type?

**Comment by nitrodynamite18** [comment]
This recipe is for compatibility with the Just Enough Effect Descriptions mod. You should be able to safely ignore this error.

**Comment by nitrodynamite18** [comment]
Fixed in commit 965.
