### ISSUE TITLE
[1.19.2 Fabric] Sounds.json broken

### ISSUE THREAD

**Issue by itsdinkd** [KyaniteMods/DeeperAndDarker#127]
1.1.6
ez fix but wanted to make you aware of this issue
```java
[17:38:02] [Worker-Main-11/WARN]: Invalid sounds.json in resourcepack: 'Deeper and Darker'
com.google.gson.JsonSyntaxException: duplicate key: block.sculk_jaw.break
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:190) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.9.jar:?]
	at net.minecraft.class_3518.method_15273(class_3518.java:521) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15297(class_3518.java:539) ~[client-intermediary.jar:?]
	at net.minecraft.class_1144.method_18180(class_1144.java:68) ~[client-intermediary.jar:?]
	at net.minecraft.class_1144.method_18789(class_1144.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18791(class_4080.java:11) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
	```

**Comment by nitrodynamite18** [comment]
Fixed by a recent pull request.
