### ISSUE TITLE
Sculk Snapper Ticking entity

### ISSUE THREAD

**Issue by WojakGra** [KyaniteMods/DeeperAndDarker#149]
**Mod Version**: 1.1.6
**Mod Loader**: fabric

**Description**:
After a friend tried to tame a sculk snapper server crashed and if somebody is close to 100 block to place where it is the server and client crashes. I tried to kill him by command and it was successful but entity was still there

Time: 2023-03-26 21:38:23
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1309.method_5739(net.minecraft.class_1297)" because the return value of "com.kyanite.deeperdarker.registry.entities.custom.SculkSnapperEntity.method_6177()" is null
	at com.kyanite.deeperdarker.registry.entities.custom.SculkSnapperEntity.method_5773(SculkSnapperEntity.java:128)
	at net.minecraft.class_638.method_18646(class_638.java:267)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_638.method_32124(class_638.java:250)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:246)
	at net.minecraft.class_310.method_1574(class_310.java:1851)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by WojakGra** [comment]
Is there a way to delete him completely?

**Comment by nitrodynamite18** [comment]
You'll have to delete the chunk where the Snapper is. This issue has been fixed and a hotfix will be releasing soon.

**Comment by WojakGra** [comment]
Ok, but I have a question because I don't know exactly how chunks work. If this chunk is first, i.e. where the portal is, what will it be called?

**Comment by ignissak** [comment]
Will this ever be fixed? bump

**Comment by Codeynn** [comment]
still not fixed

**Comment by TruheKepf** [comment]
still not fixed.

**Comment by NewJumper** [comment]
temporary fix until the next update is to use `/kill @e[type=deeperdarker:sculk_snapper]`

**Comment by Pedro270707** [comment]
Fixed in 1.2.1

**Comment by xArkailzx** [comment]
Sorry, but the issue is up again in ATM9 with a shattered

ATM9 Version: 0.2.55
Mod Version: 1.2.1

Time: 2024-04-06 15:45:33
Description: Ticking entity

java.lang.IllegalArgumentException: Cannot get property IntegerProperty{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]} as it does not exist$
        at net.minecraft.world.level.block.state.StateHolder.m_61143_(StateHolder.java:98) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ferriteco$
        at net.minecraft.world.level.block.GrowingPlantHeadBlock.m_213898_(GrowingPlantHeadBlock.java:38) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:classloading}
        at wayoftime.bloodmagic.potion.BMPotionUtils.damageMobAndGrowSurroundingPlants(BMPotionUtils.java:59) ~[bloodmagic-1.20.1-3.3.2-44.jar%23571!/:1.20.1-3.3.2-44] {re:classloading}
        at wayoftime.bloodmagic.potion.PotionPlantLeech.m_6742_(PotionPlantLeech.java:16) ~[bloodmagic-1.20.1-3.3.2-44.jar%23571!/:1.20.1-3.3.2-44] {re:classloading}
        at net.minecraft.world.effect.MobEffectInstance.m_19550_(MobEffectInstance.java:204) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:potion,re:classloading,pl:accesstransformer:B,$
        at net.minecraft.world.effect.MobEffectInstance.m_19552_(MobEffectInstance.java:171) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:potion,re:classloading,pl:accesstransformer:B,$
        at net.minecraft.world.entity.LivingEntity.m_21217_(LivingEntity.java:758) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:voidscape:attributes,re:classloading,pl:accesstransformer:B,xf$
        at net.minecraft.world.entity.LivingEntity.m_6075_(LivingEntity.java:432) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:voidscape:attributes,re:classloading,pl:accesstransformer:B,xf:$
        at net.minecraft.world.entity.Mob.m_6075_(Mob.java:271) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mix$
        at net.minecraft.world.entity.Entity.m_8119_(Entity.java:422) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,$
        at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2259) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:voidscape:attributes,re:classloading,pl:accesstransformer:B,xf$
        at net.minecraft.world.entity.Mob.m_8119_(Mob.java:337) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mix$
        at com.kyanite.deeperdarker.content.entities.Shattered.m_8119_(Shattered.java:99) ~[deeperdarker-forge-1.20.1-1.2.1.jar%23631!/:1.2.1] {re:classloading}
        at net.minecraft.server.level.ServerLevel.observable$track(ServerLevel.java:8669) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,$
        at net.minecraft.server.level.ServerLevel.redirect$bok000$observable$onTickNonPassenger(ServerLevel.java:8685) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classlo$
        at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:lib$
        at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:computing_frames,pl:accesstransformer:B,xf:fml:twilig$
        at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:l$
        at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:classloading}
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:lib$
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstr$
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,p$
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstr$
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:access$
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:access$
        at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}
        
-- Entity being ticked --
Details:
        Entity Type: deeperdarker:shattered (com.kyanite.deeperdarker.content.entities.Shattered)
        Entity ID: 1644
        Entity Name: Shattered
        Entity's Exact location: -1895.69, 30.00, -1108.55
        Entity's Block location: World: (-1896,30,-1109), Section: (at 8,14,11 in -119,1,-70; chunk contains blocks -1904,0,-1120 to -1889,127,-1105), Region: (-4,-3; contains chunks -128,-96 to -97,-65, blocks -2048,0,-1536 to -1537,12$
        Entity's Momentum: 0.00, -0.08, 0.09
        Entity's Passengers: []
        Entity's Vehicle: null
Stacktrace:
        at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:computing_frames,pl:accesstransformer:B,xf:fml:twilig$
        at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:l$
        at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:classloading}
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:lib$
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstr$
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,p$
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstr$
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:access$
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23939!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:access$
        at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}

**Comment by NewJumper** [comment]
this not related to the sculk snapper nor is it fabric. open a new issue
