### ISSUE TITLE
Sculk Transmitter causing crash to desktop after relaunching the game. 

### ISSUE THREAD

**Issue by Fishpit** [KyaniteMods/DeeperAndDarker#191]
**Mod Version**: deeperdarker-forge-1.20.1-1.2.0

**Mod Loader**: forge

**Description**:
Hovering with mouse over Sculk Transmitter causes crash to desktop.

**To Reproduce**:
Steps to reproduce the behaviour:
1. Acquire Sculk Transmitter and Link to Enchanting Table, make sure it works all fine.
2. Quit the game, close Minecraft. 
3. Reload Minecraft, join the server, or single player world.
4. Hover over Sculk Transmitter and crash.

**Additional context**:
I haven't tested it with any other linked blocks. I am running ATM 9 and it includes the Apotheosis mod which edits the enchanting table. Not sure if this matters.

**Comment by NewJumper** [comment]
I wasn't able to recreate this with the vanilla enchanting table, so it could be compatibility issues with Apotheosis. Is this issue present for other containers like chests, furnaces, etc.?

**Comment by NewJumper** [comment]
I just tested with Deeper Darker and Apotheosis and I wasn't able to recreate it again. Is there a crash log you can provide?

**Comment by NewJumper** [comment]
Oh wait, I just saw the crash log on ATM 9 issue. It might be related to the fact that Apotheosis is still in an alpha state for 1.20.1. But again, I just tested with Apotheosis and there was no crash. So possibly Apotheosis fixed it.

**Comment by NewJumper** [comment]
Could you try recreating this issue again on the latest Apotheosis and Deeper Darker version? See if this issue still persists.

**Comment by Newlyman13** [comment]
I've been having the same issue, I don't use "Apotheosis" though, here's the crash report:

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2023-09-30 10:50:03
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.Block.m_49954_()" because "this.linkedBlock" is null
	at com.kyanite.deeperdarker.content.items.SculkTransmitterItem.m_7373_(SculkTransmitterItem.java:64) ~[deeperdarker-forge-1.20.1-1.2.0.jar%23292!/:1.2.0] {re:classloading}
	at net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:631) ~[client-1.20.1-20230612.114412-srg.jar%23368!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:mixins.customizableelytra.common.json:ItemStackMixin,pl:mixin:APP:attributeslib.mixins.json:ItemStackMixin,pl:mixin:APP:mixins.mlib.json:MixinItemStack,pl:mixin:A}
	at net.minecraft.client.gui.screens.Screen.m_280152_(Screen.java:246) ~[client-1.20.1-20230612.114412-srg.jar%23368!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_280553_(AbstractContainerScreen.java:169) ~[client-1.20.1-20230612.114412-srg.jar%23368!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:attributeslib.mixins.json:client.AbstractContainerScreenMixin,pl:mixin:APP:tia.mixins.json:AbstractContainerScreenMixin,pl:mixin:APP:mousetweaks.mixins.json:AbstractContainerScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_280072_(AbstractContainerScreen.java:163) ~[client-1.20.1-20230612.114412-srg.jar%23368!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:attributeslib.mixins.json:client.AbstractContainerScreenMixin,pl:mixin:APP:tia.mixins.json:AbstractContainerScreenMixin,pl:mixin:APP:mousetweaks.mixins.json:AbstractContainerScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.InventoryScreen.m_88315_(InventoryScreen.java:80) ~[client-1.20.1-20230612.114412-srg.jar%23368!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pehkui.mixins.json:client.compat120plus.InventoryScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23368!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:423) ~[forge-1.20.1-47.1.1-universal.jar%23373!/:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:416) ~[forge-1.20.1-47.1.1-universal.jar%23373!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:965) ~[client-1.20.1-20230612.114412-srg.jar%23368!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23368!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pickupnotifier.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:itemphysic.mixins.json:MinecraftMixin,pl:mixin:APP:tofucraft.mixins.json:client.MinecraftMixin,pl:mixin:APP:playerrevive.mixins.json:MinecraftAccessor,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23368!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pickupnotifier.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:itemphysic.mixins.json:MinecraftMixin,pl:mixin:APP:tofucraft.mixins.json:client.MinecraftMixin,pl:mixin:APP:playerrevive.mixins.json:MinecraftAccessor,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.1.1.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.1.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.1.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.kyanite.deeperdarker.content.items.SculkTransmitterItem.m_7373_(SculkTransmitterItem.java:64) ~[deeperdarker-forge-1.20.1-1.2.0.jar%23292!/:1.2.0] {re:classloading}
	at net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:631) ~[client-1.20.1-20230612.114412-srg.jar%23368!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:mixins.customizableelytra.common.json:ItemStackMixin,pl:mixin:APP:attributeslib.mixins.json:ItemStackMixin,pl:mixin:APP:mixins.mlib.json:MixinItemStack,pl:mixin:A}
	at net.minecraft.client.gui.screens.Screen.m_280152_(Screen.java:246) ~[client-1.20.1-20230612.114412-srg.jar%23368!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_280553_(AbstractContainerScreen.java:169) ~[client-1.20.1-20230612.114412-srg.jar%23368!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:attributeslib.mixins.json:client.AbstractContainerScreenMixin,pl:mixin:APP:tia.mixins.json:AbstractContainerScreenMixin,pl:mixin:APP:mousetweaks.mixins.json:AbstractContainerScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_280072_(AbstractContainerScreen.java:163) ~[client-1.20.1-20230612.114412-srg.jar%23368!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:attributeslib.mixins.json:client.AbstractContainerScreenMixin,pl:mixin:APP:tia.mixins.json:AbstractContainerScreenMixin,pl:mixin:APP:mousetweaks.mixins.json:AbstractContainerScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.InventoryScreen.m_88315_(InventoryScreen.java:80) ~[client-1.20.1-20230612.114412-srg.jar%23368!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pehkui.mixins.json:client.compat120plus.InventoryScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23368!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:423) ~[forge-1.20.1-47.1.1-universal.jar%23373!/:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:416) ~[forge-1.20.1-47.1.1-universal.jar%23373!/:?] {re:classloading}

**Comment by NewJumper** [comment]
do you remember what you did to produce that crash?

**Comment by claviger** [comment]
I have the same issue (this.linkedblock is null), and also don't run Apotheosis. In my case, all I did was link the Skulk Transmitter to a double chest in a multiplayer game, and later log off. When I logged back on again, the Transmitter still has the graphic of being linked, but if I so much as mouse over it the game immediately crashes.

**Comment by NewJumper** [comment]
I still am unable to reproduce the issue. I even tested on singleplayer and on a server.
I linked to a double chest, logged off, then logged back on. Hovering over the transmitter did not crash my game.

**Comment by claviger** [comment]
We'll keep playing with it and see if we can figure out what's causing it. But 3 different players on my server now have skulk transmitters that worked for a while but are now in the game-crashing bad state, so something's causing it to recur.

**Comment by Fishpit** [comment]
> I still am unable to reproduce the issue. I even tested on singleplayer and on a server. I linked to a double chest, logged off, then logged back on. Hovering over the transmitter did not crash my game.

For me this only happened when I completely closed Minecraft as stated in my original post. 

Only other variable I can think of is if the linked block is in a FTB claimed area? Other than that no clue to what's going on or why you cant repeat this.

**Comment by NewJumper** [comment]
Ah, got it! It does happen when you close the game and rejoin. Looking into it now!
