### ISSUE TITLE
[1.20.1 Forge] Server tick timeout crash

### ISSUE THREAD

**Issue by MrKashew** [KyaniteMods/DeeperAndDarker#194]
[crash-2023-08-29_22.19.52-server.txt](https://github.com/KyaniteMods/DeeperAndDarker/files/12471950/crash-2023-08-29_22.19.52-server.txt)
Timeout in DeeperDarker dim
The portion that's likely useful
```

"Worker-Main-7" daemon prio=5 Id=92 RUNNABLE
	at java.base@17.0.7/jdk.internal.misc.Unsafe.unpark(Native Method)
	at java.base@17.0.7/java.util.concurrent.locks.LockSupport.unpark(LockSupport.java:177)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6937_(BlockableEventLoop.java:94)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:100)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.handler$bld000$onOnBlockChanged(ServerLevel.java:6652)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_6559_(ServerLevel.java)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.WorldGenRegion.m_6933_(WorldGenRegion.java:264)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.LevelWriter.m_7731_(LevelWriter.java:15)
	at TRANSFORMER/deeperdarker@1.2.0/com.kyanite.deeperdarker.world.features.GloomslateColumnFeature.stretchToFloor(GloomslateColumnFeature.java:133)
	at TRANSFORMER/deeperdarker@1.2.0/com.kyanite.deeperdarker.world.features.GloomslateColumnFeature.columnBase(GloomslateColumnFeature.java:88)
	at TRANSFORMER/deeperdarker@1.2.0/com.kyanite.deeperdarker.world.features.GloomslateColumnFeature.m_142674_(GloomslateColumnFeature.java:63)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.levelgen.feature.Feature.m_225028_(Feature.java:155)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.levelgen.feature.ConfiguredFeature.m_224953_(ConfiguredFeature.java:28)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226362_(PlacedFeature.java:54)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.levelgen.placement.PlacedFeature$$Lambda$45115/0x000000080563dd28.accept(Unknown Source)
	at java.base@17.0.7/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base@17.0.7/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base@17.0.7/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base@17.0.7/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base@17.0.7/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base@17.0.7/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base@17.0.7/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base@17.0.7/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base@17.0.7/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base@17.0.7/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base@17.0.7/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base@17.0.7/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
	at java.base@17.0.7/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base@17.0.7/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711)
	at java.base@17.0.7/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base@17.0.7/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base@17.0.7/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base@17.0.7/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base@17.0.7/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base@17.0.7/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base@17.0.7/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base@17.0.7/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base@17.0.7/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base@17.0.7/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base@17.0.7/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base@17.0.7/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base@17.0.7/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base@17.0.7/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226368_(PlacedFeature.java:53)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.levelgen.placement.PlacedFeature.m_226377_(PlacedFeature.java:42)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.ChunkGenerator.m_213609_(ChunkGenerator.java:357)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.ChunkStatus.m_279978_(ChunkStatus.java:108)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.ChunkStatus$$Lambda$2592/0x00000008015f3a50.m_156322_(Unknown Source)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.m_214024_(ChunkStatus.java:309)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.ChunkStatus.m_280308_(ChunkStatus.java:252)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:643)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ChunkMap$$Lambda$44599/0x00000008055c1178.apply(Unknown Source)
	at MC-BOOTSTRAP/datafixerupper@6.0.8/com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$29(ChunkMap.java:634)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ChunkMap$$Lambda$44561/0x00000008055b8d00.apply(Unknown Source)
	at java.base@17.0.7/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base@17.0.7/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ChunkTaskPriorityQueueSorter$$Lambda$44597/0x00000008055c0d28.run(Unknown Source)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102)
	at java.base@17.0.7/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base@17.0.7/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base@17.0.7/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base@17.0.7/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base@17.0.7/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base@17.0.7/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)


"Server thread" prio=8 Id=95 RUNNABLE
	at java.base@17.0.7/java.lang.Thread.yield(Native Method)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_5667_(BlockableEventLoop.java:150)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:141)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerChunkCache.m_7587_(ServerChunkCache.java:131)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_6522_(Level.java:187)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_7925_(Level.java:635)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.BlockCollisions.m_186411_(BlockCollisions.java:62)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.BlockCollisions.computeNext(BlockCollisions.java:81)
	at MC-BOOTSTRAP/com.google.common@31.1-jre/com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at MC-BOOTSTRAP/com.google.common@31.1-jre/com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at MC-BOOTSTRAP/com.google.common@31.1-jre/com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:464)
	at MC-BOOTSTRAP/com.google.common@31.1-jre/com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:868)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_198894_(Entity.java:927)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_20272_(Entity.java:891)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Entity.m_6478_(Entity.java:632)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_7185_(ServerGamePacketListenerImpl.java:911)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.m_5797_(ServerboundMovePlayerPacket.java:114)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.m_5797_(ServerboundMovePlayerPacket.java:42)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.PacketUtils$$Lambda$49209/0x0000000805a6a078.run(Unknown Source)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.TickTask.run(TickTask.java:18)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:732)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer$$Lambda$44152/0x0000000805498cf8.run(Unknown Source)
	at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
```

**Comment by NewJumper** [comment]
please follow proper bug reporting guidelines
