### ISSUE TITLE
Invalid sounds.json

### ISSUE THREAD

**Issue by DEAFG0AT** [KyaniteMods/DeeperAndDarker#207]
**Mod Version**: 1.19.2
**Mod Loader**: Fabric

**Description**:
I'm getting loads of warnings about textures and sounds not being properly loaded for Deeper and Darker. Playing through the game, I've also noticed that Sculk stone variants and some other blocks don't have sounds when you break or place them (I think I may have already submitted a bug report for the missing sounds, but I don't remember).

**To Reproduce**:
1. Install Deeper and Darker fabric version 1.1.6.
2. Launch Minecraft.
3. Open latest.log and observe the warnings.

**Log Excerpt**:
[01:01:29] [Worker-ResourceReload-7/WARN]:
 File beachparty:sounds/ambient_beach.ogg does not exist, cannot add it to event beachparty:ambient_beach
**[01:01:29] [Worker-ResourceReload-10/ERROR]:
 Non [a-z0-9/._-] character in path of location: deeperdarker:animations/VoxelShape.java**
[01:01:29] [Worker-ResourceReload-7/WARN]:
 Invalid sounds.json in resourcepack: 'Deeper and Darker'
com.google.gson.JsonSyntaxException: duplicate key: block.sculk_jaw.break
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:190) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.9.jar:?]
	at net.minecraft.class_3518.method_15273(class_3518.java:521) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15297(class_3518.java:539) ~[client-intermediary.jar:?]
	at net.minecraft.class_1144.method_18180(class_1144.java:68) ~[client-intermediary.jar:?]
	at net.minecraft.class_1144.method_18789(class_1144.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18791(class_4080.java:11) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]

**Full Log**: https://mclo.gs/k1LQUha

![image](https://github.com/KyaniteMods/DeeperAndDarker/assets/104733108/07ed302b-1fb4-4134-b436-4515b183c67c)

**Comment by NewJumper** [comment]
fixed in 1.2.1
