### ISSUE TITLE
Crashing to desktop after equipping warden helmet.

### ISSUE THREAD

**Issue by Frosk-Kristian** [KyaniteMods/DeeperAndDarker#246]
**Minecraft Version**: 1.19.2
**Mod Version**: 1.2.3
**Mod Loader**: fabric

**Description**:
Attempting to view my character (including the preview in the inventory screen) after equipping a warden helmet is crashing my game to desktop. I do not know if the other armour pieces also trigger this.
I am using Quilt.

**To Reproduce**:
1. Load into a creative save.
2. Equip a warden helmet.
3. Attempt to open inventory after doing so.
4. Game crashes.

After doing this, loading into the same save and opening your inventory again will cause the same crash.

**Additional context**:
Here's the part of the log that I believe relates to this issue:
```[17:54:02] [Render thread/INFO]: Stopping worker threads
[17:54:02] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering entity in world
	at net.minecraft.class_757.method_3192(class_757.java:890) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1177) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [transformed-mod-minecraft-v1.19.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551) [quilt-loader-0.22.0-beta.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84) [quilt-loader-0.22.0-beta.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) [quilt-loader-0.22.0-beta.1.jar:?]
Caused by: net.minecraft.class_151: Non [a-z0-9_.-] character in namespace of location: textures/models/armor/deeperdarker:warden_layer_1.png
	at net.minecraft.class_2960.<init>(class_2960.java:38) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_2960.<init>(class_2960.java:46) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at java.util.HashMap.computeIfAbsent(Unknown Source) ~[?:?]
	at net.minecraft.class_970.handler$bem000$chime$getArmorTexture(class_970.java:3053) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_970.method_4174(class_970.java) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_970.method_23192(class_970.java:105) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_970.method_4169(class_970.java:70) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_970.method_17157(class_970.java:38) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_970.method_4199(class_970.java:22) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_922.method_4054(class_922.java:145) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_1007.method_4215(class_1007.java:63) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_1007.method_3936(class_1007.java:41) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_898.method_3954(class_898.java:141) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_490.method_29977(class_490.java:152) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1171) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_490.method_2486(class_490.java:152) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_481.method_2389(class_481.java:768) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_465.method_25394(class_465.java:100) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_485.method_25394(class_485.java:27) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_481.method_25394(class_481.java:679) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:881) ~[transformed-mod-minecraft-v1.19.2.jar:?]
	... 11 more
```

I've also attached the full crash log below.
[Crash Log.txt](https://github.com/KyaniteMods/DeeperAndDarker/files/13457874/Crash.Log.txt)

**Comment by Pedro270707** [comment]
Fixed in 1.2.4
