### ISSUE TITLE
Renamed sculk transmitter crashed the game

### ISSUE THREAD

**Issue by EmilAhmaBoy** [KyaniteMods/DeeperAndDarker#316]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.2.6
**Mod Loader**: fabric

**Description**:
Sculk Transmitter bug. Game crashes when trying to rename sculk transmitter and unlinking it from the container.

**To Reproduce**:
1. Link the sculk transmitter to the container
2. Rename it in the anvil
3. Unlink it
Now this sculk transmitter is cursed .'/

**Additional context**:
```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.kyanite.deeperdarker.content.items.SculkTransmitterItem.transmit(SculkTransmitterItem.java:74)
	at com.kyanite.deeperdarker.content.items.SculkTransmitterItem.method_7836(SculkTransmitterItem.java:54)
	at net.minecraft.class_1799.method_7913(class_1799.java:284)
	at net.minecraft.class_636.method_41929(class_636.java:387)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2919(class_636.java:379)
	at net.minecraft.class_310.method_1583(class_310.java:1822)
	at net.minecraft.class_310.method_1508(class_310.java:2052)
	at net.minecraft.class_310.method_1574(class_310.java:1883)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by EmilAhmaBoy** [comment]
Ok, #280 fixes that as I understood but IDK in which release it was or will be

**Comment by NewJumper** [comment]
the next update, whenever it releases
