### ISSUE TITLE
Host Server Crashed 

### ISSUE THREAD

**Issue by MonroyMGZ** [KyaniteMods/DeeperAndDarker#337]
Minecraft Version: 1.20.1
Mod Version: 1.3.0
Mod Loader: Forge

I was triying to play the 1.3.0 version for Forge in my host server, I had the last version and I have already back it up, but then now I can't enter to my server, it displays a message that says "internal server error" and when I talked with one of the hosters they told me that was the new Deeper & Darker version the one who is causing this error. 
![imagen_2024-08-21_165816531](https://github.com/user-attachments/assets/bad320dc-09e2-4aca-99b3-ab2d002eb009)

Log Error: 
[12:52:27] [Server thread/WARN] [minecraft/ServerConnectionListener]: Failed to handle packet for .....
net.minecraft.ReportedException: Ticking player
at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:530) ~[server-1.20.1-20230612.114412-srg.jar%23329!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendisland.mixins.json:ServerPlayerMixin,pl:mixin:APP:netherportalfix.mixins.json:ServerPlayerMixin,pl:mixin:APP:netherportalfix.mixins.json:ForgeServerPlayerMixin,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:playerrevive.mixins.json:ServerPlayerMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerPlayerTickMixin,pl:mixin:APP:tombstone.mixins.json:ServerPlayerMixin,pl:mixin:APP:securitycraft.mixins.json:camera.ServerPlayerMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.ServerPlayerMixin,pl:mixin:A}
at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:262) ~[server-1.20.1-20230612.114412-srg.jar%23329!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:railways.mixins.json:ServerGamePacketListenerImplMixin,pl:mixin:APP:forge-mca.mixin.json:MixinServerPlayNetworkHandler,pl:mixin:A}
at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[server-1.20.1-20230612.114412-srg.jar%23329!/:?] {re:mixin,re:classloading}
at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.20.1-20230612.114412-srg.jar%23329!/:?] {re:classloading}
at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[server-1.20.1-20230612.114412-srg.jar%23329!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23329!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A}
at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23329!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23329!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23329!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin}
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.3.0.jar%2369!/:1.0] {}
at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2355!/:?] {}
at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2355!/:?] {}
at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2355!/:?] {}
at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
at com.kyanite.deeperdarker.content.items.SoulElytraItem.m_6883_(SoulElytraItem.java:43) ~[deeperdarker-forge-1.20.1-1.3.0.jar%23244!/:1.3.0] {re:classloading}
at net.minecraft.world.item.ItemStack.m_41666_(ItemStack.java:481) ~[server-1.20.1-20230612.114412-srg.jar%23329!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:tombstone.mixins.json:ItemStackMixin,pl:mixin:APP:mixins.deeperdarker.json:ItemStackMixin,pl:mixin:A} at top.theillusivec4.curios.common.event.CuriosEventHandler.lambda$tick$35(CuriosEventHandler.java:576) ~[curios-forge-5.9.1+1.20.1.jar%23243!/:5.9.1+1.20.1] {re:classloading}
at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:137) ~[forge-1.20.1-47.3.0-universal.jar%23334!/:?] {re:mixin,re:classloading}
at top.theillusivec4.curios.common.event.CuriosEventHandler.tick(CuriosEventHandler.java:556) ~[curios-forge-5.9.1+1.20.1.jar%23243!/:5.9.1+1.20.1] {re:classloading}
at top.theillusivec4.curios.common.event.__CuriosEventHandler_tick_LivingTickEvent.invoke(.dynamic) ~[curios-forge-5.9.1+1.20.1.jar%23243!/:5.9.1+1.20.1] {re:classloading,pl:eventbus:B}
at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?] {}
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?] {}
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?] {}
at net.minecraftforge.common.ForgeHooks.onLivingTick(ForgeHooks.java:264) ~[forge-1.20.1-47.3.0-universal.jar%23334!/:?] {re:classloading}
at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2258) ~[server-1.20.1-20230612.114412-srg.jar%23329!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:netherportalfix.mixins.json:LivingEntityAccessor,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:cataclysm.mixins.json:LivingEntityMixin,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:tombstone.mixins.json:LivingEntityMixin,pl:mixin:APP:mermod-common.mixins.json:LivingEntityMixin,pl:mixin:APP:lithium.mixins.json:alloc.enum_values.living_entity.LivingEntityMixin,pl:mixin:APP:lithium.mixins.json:entity.collisions.unpushable_cramming.LivingEntityMixin,pl:mixin:APP:lithium.mixins.json:entity.fast_elytra_check.LivingEntityMixin,pl:mixin:APP:lithium.mixins.json:entity.fast_hand_swing.LivingEntityMixin,pl:mixin:APP:lithium.mixins.json:entity.fast_powder_snow_check.LivingEntityMixin,pl:mixin:APP:lithium.mixins.json:entity.skip_equipment_change_check.LivingEntityMixin,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:betterdeserttemples.mixins.json:PharaohKilledMixin,pl:mixin:APP:mixins.bosses_of_mass_destruction.json:LivingEntityMixin,pl:mixin:APP:alexscaves.mixins.json:LivingEntityMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinLivingEntity,pl:mixin:APP:charmofundying.mixins.json:MixinLivingEntity,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:APP:create.mixins.json:LavaSwimmingMixin,pl:mixin:APP:create.mixins.json:accessor.LivingEntityAccessor,pl:mixin:A}
at net.minecraft.world.entity.player.Player.m_8119_(Player.java:241) ~[server-1.20.1-20230612.114412-srg.jar%23329!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:railways-common.mixins.json:MixinPlayer,pl:mixin:APP:railways-common.mixins.json:PlayerEntityMixin,pl:mixin:APP:carryon.mixins.json:PlayerMixin,pl:mixin:APP:tombstone.mixins.json:PlayerMixin,pl:mixin:APP:playerrevive.mixins.json:PlayerMixin,pl:mixin:APP:forge-mca.mixin.json:MixinPlayerEntity,pl:mixin:APP:easymagic.common.mixins.json:accessor.PlayerAccessor,pl:mixin:APP:cloudboots.mixins.json:PlayerMixin,pl:mixin:A}
at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467) ~[server-1.20.1-20230612.114412-srg.jar%23329!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendisland.mixins.json:ServerPlayerMixin,pl:mixin:APP:netherportalfix.mixins.json:ServerPlayerMixin,pl:mixin:APP:netherportalfix.mixins.json:ForgeServerPlayerMixin,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:playerrevive.mixins.json:ServerPlayerMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerPlayerTickMixin,pl:mixin:APP:tombstone.mixins.json:ServerPlayerMixin,pl:mixin:APP:securitycraft.mixins.json:camera.ServerPlayerMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.ServerPlayerMixin,pl:mixin:A}
... 9 more
[12:52:27] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: MonroyMGZ lost connection: Internal server error
[12:52:27] [Server thread/INFO] [minecraft/MinecraftServer]: MonroyMGZ left the game
[12:52:27] [Server thread/INFO] [me.ed.sk.se.SkinProviderController/]: Removing session data for player MonroyMGZ[79ab55c3-622d-3cba-a6e4-e798e4eb23de]

**Comment by NewJumper** [comment]
Was Deeper and Darker the only mod you had installed?

**Comment by MonroyMGZ** [comment]
No, I have other 100 mods add but I was playing good with the Deeper & Darker 1.2.1 and when I tried to upgrade it to the newer version now I can't play

**Comment by NewJumper** [comment]
what were the steps to recreate the error

**Comment by MonroyMGZ** [comment]
Well, first I have been playing on that host server for two months with the 1.2.1 Forge Deeper & Darker, then yesterday when the new version was released "1.3.0" I just delete from the server mods the previous Deeper & Darker and added the new one, but then when I tried to enter it doesn't allow me to do it. I almost forgot to say that I backed up my world before, but I'm just waiting If I could play with the new version or no

**Comment by NewJumper** [comment]
could you try recreating this issue with a new world

**Comment by NewJumper** [comment]
this seems like a compatibility issue, but we'll see

**Comment by MonroyMGZ** [comment]
In a Single world it works perfectly, but not in the host server so that's why I asked the hosters but they told me that was something more internal with the Deeper & Darker

**Comment by BanTheWeeb** [comment]
I've Encountered a similar issue with my server only mine crashed the moment i grabbed the soul elytra so i think the bug might lie there

**Comment by NewJumper** [comment]
so its with the soul elytra? i got nothing here. i need more details on how to recreate this

**Comment by BanTheWeeb** [comment]
All i can tell is that on my server everything worked fine i then grabbed a soul elytra out of my creative menu and then it kicked me out of the game and would not let me join back in again i had to reset my world

**Comment by MonroyMGZ** [comment]
Well in my host server I'm wearing all the full set and with the mod "ElitraSlot" the soul elytra but I tried enter first with the back up, I took off the soul elytra and tried to reinstall the new version but it was the same issue, I couldn't get into my host server.

**Comment by aaron01-dev** [comment]
Also experiencing the same thing, same mc, forge, and mod version, the only mods I can think of that are affecting this is the elytra slot and curios
