### ISSUE TITLE
Crashed while loading terrain in a server

### ISSUE THREAD

**Issue by AmbrusSynth** [KyaniteMods/DeeperAndDarker#380]
**Minecraft Version**: 1.20.1
**Mod Version**: 1.3.1
**Mod Loader**: Forge

**Description**:
Upon taking damage the server would crash. then whenever i would try and reload it would continue to crash the server

**To Reproduce**:
not really sure how to reproduce 
but i do have logs

---- Minecraft Crash Report ----                 1 // Daisy, daisy...                             3                                                    1 Time: 2024-10-19 17:07:33                        2 Description: Ticking entity                      3                                                  4 java.lang.AbstractMethodError: Receiver class c    om.mna.items.armor.MAArmorMaterial does not def    ine or inherit an implementation of the resolve    d method 'abstract java.lang.String m_6082_()'     of interface net.minecraft.world.item.ArmorMate    rial.                                            5 »···at com.kyanite.deeperdarker.DeeperDarkerEve    nts.livingDamageEvent(DeeperDarkerEvents.java:1    45) ~[deeperdarker-forge-1.20.1-1.3.1.jar%23327    !/:1.3.1] {re:classloading}                      6 »···at com.kyanite.deeperdarker.__DeeperDarkerE    vents_livingDamageEvent_LivingDamageEvent.invok    e(.dynamic) ~[deeperdarker-forge-1.20.1-1.3.1.j    ar%23327!/:1.3.1] {re:classloading,pl:eventbus:    B}
...

null[18Oct2024 17:52:44.600] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, {MINECRAFT_USERNAME}, --version, 1.20.1, --gameDir, C:\Users\ryonh\AppData\Roaming\ModrinthApp\profiles\Of Fluff and Magic, --assetsDir, C:\Users\ryonh\AppData\Roaming\ModrinthApp\meta\assets, --assetIndex, 5, --uuid, {MINECRAFT_UUID}, --accessToken, ????????, --clientId, c4502edb-87c6-40cb-b595-64a280cf8906, --xuid, 0, --userType, msa, --versionType, release, --width, 854, --height, 480, --launchTarget, forgeclient, --fml.forgeVersion, 47.3.11, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[18Oct2024 17:52:44.604] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.11 by Azul Systems, Inc.; OS Windows 10 arch amd64 version 10.0
[18Oct2024 17:52:45.878] [main/INFO] [net.minecraftforge.fml.loading.ImmediateWindowHandler/]: Loading ImmediateWindowProvider fmlearlywindow
[18Oct2024 17:52:45.977] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.6
[18Oct2024 17:52:46.188] [main/INFO] [EARLYDISPLAY/]: Requested GL version 4.6 got version 4.6
[18Oct2024 17:52:46.314] [pool-2-thread-1/INFO] [EARLYDISPLAY/]: GL info: NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 565.90, NVIDIA Corporation
[18Oct2024 17:52:46.685] [main/INFO] [gg.essential.loader.stage1.EssentialLoaderBase/]: Starting Essential Loader (stage2) version 1.6.3 (285f951adc7537f49ae3ef9fc0d2fd3e) [stable]
[18Oct2024 17:52:46.727] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/ryonh/AppData/Roaming/ModrinthApp/meta/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2394!/ Service=ModLauncher Env=CLIENT
[18Oct2024 17:52:47.610] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\ryonh\AppData\Roaming\ModrinthApp\meta\libraries\net\minecraftforge\fmlcore\1.20.1-47.3.11\fmlcore-1.20.1-47.3.11.jar is missing mods.toml file
[18Oct2024 17:52:47.613] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\ryonh\AppData\Roaming\ModrinthApp\meta\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.3.11\javafmllanguage-1.20.1-47.3.11.jar is missing mods.toml file
[18Oct2024 17:52:47.615] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\ryonh\AppData\Roaming\ModrinthApp\meta\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.3.11\lowcodelanguage-1.20.1-47.3.11.jar is missing mods.toml file
[18Oct2024 17:52:47.618] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\ryonh\AppData\Roaming\ModrinthApp\meta\libraries\net\minecraftforge\mclanguage\1.20.1-47.3.11\mclanguage-1.20.1-47.3.11.jar is missing mods.toml file
[18Oct2024 17:52:48.001] [main/WARN] [net.minecraftforge.jarjar.selection.JarSelector/]: Attempted to select two dependency jars from JarJar which have the same identification: Mod File:  and Mod File: . Using Mod File: 
[18Oct2024 17:52:48.001] [main/WARN] [net.minecraftforge.jarjar.selection.JarSelector/]: Attempted to select two dependency jars from JarJar which have the same identification: Mod File:  and Mod File: . Using Mod File: 
[18Oct2024 17:52:48.003] [main/WARN] [net.minecraftforge.jarjar.selection.JarSelector/]: Attempted to select a dependency jar for JarJar which was passed in as source: curios. Using Mod File: C:\Users\ryonh\AppData\Roaming\ModrinthApp\profiles\Of Fluff and Magic\mods\curios-forge-5.10.0+1.20.1.jar
[18Oct2024 17:52:48.003] [main/WARN] [net.minecraftforge.jarjar.selection.JarSelector/]: Attempted to select a dependency jar for JarJar which was passed in as source: resourcefullib. Using Mod File: C:\Users\ryonh\AppData\Roaming\ModrinthApp\profiles\Of Fluff and Magic\mods\resourcefullib-forge-1.20.1-2.1.29.jar
[18Oct2024 17:52:48.003] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Found 29 dependencies adding them to mods collection
[18Oct2024 17:52:48.066] [main/INFO] [gg.essential.loader.stage2.util.KFFMerger/]: Found Kotlin-containing mod Jar[union:/C:/Users/ryonh/AppData/Roaming/ModrinthApp/profiles/Of%20Fluff%20and%20Magic/essential/libraries/forge_1.20.1/kotlin-for-forge-4.3.0-slim.jar%23346!/], checking whether we need to upgrade it..
[18Oct2024 17:52:48.068] [main/INFO] [gg.essential.loader.stage2.util.KFFMerger/]: Found outdated Kotlin core libs 0.0.0 (we ship 1.9.23)
[18Oct2024 17:52:48.068] [main/INFO] [gg.essential.loader.stage2.util.KFFMerger/]: Found outdated Kotlin Coroutines libs 0.0.0 (we ship 1.8.0)
[18Oct2024 17:52:48.068] [main/INFO] [gg.essential.loader.stage2.util.KFFMerger/]: Found outdated Kotlin Serialization libs 0.0.0 (we ship 1.6.3)
[18Oct2024 17:52:48.071] [main/INFO] [gg.essential.loader.stage2.util.KFFMerger/]: Generating jar with updated Kotlin at C:\Users\ryonh\AppData\Local\Temp\kff-updated-kotlin-18421000453510781848-4.3.0-slim.jar
[18Oct2024 17:52:48.747] [main/INFO] [gg.essential.loader.stage2.util.KFFMerger/]: Found Kotlin-containing mod Jar[union:/C:/Users/ryonh/AppData/Roaming/ModrinthApp/profiles/Of%20Fluff%20and%20Magic/mods/kotlinforforge-4.11.0-all.jar%23436!/], checking whether we need to upgrade it..
[18Oct2024 17:52:48.749] [main/INFO] [gg.essential.loader.stage2.util.KFFMerger/]: Found up-to-date Kotlin core libs 2.0.0 (we ship 1.9.23)
[18Oct2024 17:52:48.749] [main/INFO] [gg.essential.loader.stage2.util.KFFMerger/]: Found up-to-date Kotlin Coroutines libs 1.8.1 (we ship 1.8.0)
[18Oct2024 17:52:48.749] [main/INFO] [gg.essential.loader.stage2.util.KFFMerger/]: Found up-to-date Kotlin Serialization libs 1.6.3 (we ship 1.6.3)
[18Oct2024 17:52:48.749] [main/INFO] [gg.essential.loader.stage2.util.KFFMerger/]: All good, no update needed: Jar[union:/C:/Users/ryonh/AppData/Roaming/ModrinthApp/profiles/Of%20Fluff%20and%20Magic/mods/kotlinforforge-4.11.0-all.jar%23436!/]
[18Oct2024 17:52:51.800] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[18Oct2024 17:52:51.961] [main/ERROR] [mixin/]: Mixin config emi_loot.mixins.json does not specify "minVersion" property
[18Oct2024 17:52:52.079] [main/ERROR] [mixin/]: Mixin config yacl.mixins.json does not specify "minVersion" property
[18Oct2024 17:52:52.094] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.20.1, --gameDir, C:\Users\ryonh\AppData\Roaming\ModrinthApp\profiles\Of Fluff and Magic, --assetsDir, C:\Users\ryonh\AppData\Roaming\ModrinthApp\meta\assets, --uuid, {MINECRAFT_UUID}, --username, {MINECRAFT_USERNAME}, --assetIndex, 5, --accessToken, ????????, --clientId, c4502edb-87c6-40cb-b595-64a280cf8906, --xuid, 0, --userType, msa, --versionType, release, --width, 854, --height, 480]
[18Oct2024 17:52:52.158] [main/INFO] [ModernFix/]: Loaded configuration file for ModernFix 5.19.4+mc1.20.1: 84 options available, 0 override(s) found
[18Oct2024 17:52:52.159] [main/INFO] [ModernFix/]: Applying Nashorn fix
[18Oct2024 17:52:52.168] [main/INFO] [ModernFix/]: Applied Forge config corruption patch
[18Oct2024 17:52:52.233] [main/WARN] [mixin/]: Reference map 'nitrogen_internals.refmap.json' for nitrogen_internals.mixins.json could not be read. If this is a development environment you can ignore this message
[18Oct2024 17:52:52.260] [main/INFO] [Essential Logger - Plugin/]: Starting Essential v1.3.4.1 (#311f9c466c) [stable]
[18Oct2024 17:52:52.331] [main/WARN] [mixin/]: Reference map 'harvest_with_ease.refmap.json' for harvest_with_ease.mixins.json could not be read. If this is a development environment you can ignore this message
[18Oct2024 17:52:52.334] [main/WARN] [mixin/]: Reference map 'harvest_with_ease.refmap.json' for harvest_with_ease.forge.mixins.json could not be read. If this is a development environment you can ignore this message
[18Oct2024 17:52:52.419] [main/WARN] [mixin/]: Reference map 'weeping_angels-forge-refmap.json' for weeping_angels.mixins.json could not be read. If this is a development environment you can ignore this message
[18Oct2024 17:52:52.459] [main/WARN] [mixin/]: Reference map 'cobweb.refmap.json' for cobweb.mixins.json could not be read. If this is a development environment you can ignore this message
[18Oct2024 17:52:52.461] [main/WARN] [mixin/]: Reference map 'cobweb.refmap.json' for cobweb.forge.mixins.json could not be read. If this is a development environment you can ignore this message
[18Oct2024 17:52:52.466] [main/WARN] [mixin/]: Reference map 'AchievementOptimizer.refmap.json' for achiopt.mixins.json could not be read. If this is a development environment you can ignore this message
[18Oct2024 17:52:52.480] [main/WARN] [mixin/]: Reference map 'colorfulhearts-common-api-api_common-refmap.json' for colorfulhearts-common.mixins.json could not be read. If this is a development environment you can ignore this message
[18Oct2024 17:52:52.525] [main/WARN] [mixin/]: Reference map 'bloodmagic.refmap.json' for bloodmagic.mixins.json could not be read. If this is a development environment you can ignore this message
[18Oct2024 17:52:52.540] [main/WARN] [mixin/]: Reference map 'simplyswords-forge-refmap.json' for simplyswords.mixins.json could not be read. If this is a development environment you can ignore this message
[18Oct2024 17:52:52.566] [main/WARN] [mixin/]: Reference map 'uilib-common-refmap.json' for uilib-common.mixins.json could not be read. If this is a development environment you can ignore this message
[18Oct2024 17:52:54.309] [main/INFO] [Colorful Hearts/]: Applying mixin HUDOverlayHandlerAccessor as mod appleskin is present.
[18Oct2024 17:52:54.309] [main/INFO] [Colorful Hearts/]: Applying mixin ComfortHealthOverlayMixin as mod farmersdelight is present.
[18Oct2024 17:52:54.419] [main/WARN] [mixin/]: Error loading class: net/fabricmc/fabric/api/entity/event/v1/FabricElytraItem (java.lang.ClassNotFoundException: net.fabricmc.fabric.api.entity.event.v1.FabricElytraItem)
[18Oct2024 17:52:54.543] [main/WARN] [mixin/]: Error loading class: noobanidus/mods/lootr/config/ConfigManager (java.lang.ClassNotFoundException: noobanidus.mods.lootr.config.ConfigManager)
[18Oct2024 17:52:54.573] [main/INFO] [memoryleakfix/]: [MemoryLeakFix] Will be applying 3 memory leak fixes!
[18Oct2024 17:52:54.573] [main/INFO] [memoryleakfix/]: [MemoryLeakFix] Currently enabled memory leak fixes: [targetEntityLeak, biomeTemperatureLeak, hugeScreenshotLeak]
[18Oct2024 17:52:54.803] [main/WARN] [mixin/]: Error loading class: org/jetbrains/annotations/ApiStatus$Internal (java.lang.ClassNotFoundException: org.jetbrains.annotations.ApiStatus$Internal)
[18Oct2024 17:52:54.819] [main/INFO] [MixinExtras|Service/]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).
[18Oct2024 17:52:56.468] [pool-4-thread-1/INFO] [net.minecraft.server.Bootstrap/]: ModernFix reached bootstrap stage (13.77 s after launch)
[18Oct2024 17:52:56.526] [pool-4-thread-1/WARN] [mixin/]: @Final field delegatesByName:Ljava/util/Map; in modernfix-forge.mixins.json:perf.forge_registry_alloc.ForgeRegistryMixin should be final
[18Oct2024 17:52:56.526] [pool-4-thread-1/WARN] [mixin/]: @Final field delegatesByValue:Ljava/util/Map; in modernfix-forge.mixins.json:perf.forge_registry_alloc.ForgeRegistryMixin should be final
[18Oct2024 17:52:57.136] [pool-4-thread-1/INFO] [net.minecraft.server.Bootstrap/]: Vanilla bootstrap took 665 milliseconds
[18Oct2024 17:52:59.295] [pool-4-thread-1/WARN] [mixin/]: Static binding violation: PRIVATE @Overwrite method m_47505_ in modernfix-common.mixins.json:perf.remove_biome_temperature_cache.BiomeMixin cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
[18Oct2024 17:52:59.494] [pool-4-thread-1/WARN] [AE2:C/]: Unable to find class com.simibubi.create.foundation.ponder.PonderWorld. Integration with PonderJS disabled.
[18Oct2024 17:53:00.006] [Render thread/WARN] [net.minecraft.server.packs.VanillaPackResourcesBuilder/]: Assets URL 'union:/C:/Users/ryonh/AppData/Roaming/ModrinthApp/meta/libraries/net/minecraft/client/1.20.1-20230612.114412/client-1.20.1-20230612.114412-srg.jar%23526!/assets/.mcassetsroot' uses unexpected schema
[18Oct2024 17:53:00.006] [Render thread/WARN] [net.minecraft.server.packs.VanillaPackResourcesBuilder/]: Assets URL 'union:/C:/Users/ryonh/AppData/Roaming/ModrinthApp/meta/libraries/net/minecraft/client/1.20.1-20230612.114412/client-1.20.1-20230612.114412-srg.jar%23526!/data/.mcassetsroot' uses unexpected schema
[18Oct2024 17:53:00.025] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18Oct2024 17:53:00.220] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: {MINECRAFT_USERNAME}
[18Oct2024 17:53:00.280] [Render thread/INFO] [ModernFix/]: Bypassed Mojang DFU
[18Oct2024 17:53:00.897] [Render thread/INFO] [Essential Logger/]: OptiFine not detected.
[18Oct2024 17:53:00.964] [Render thread/INFO] [Essential - DI/]: Starting DI!
[18Oct2024 17:53:01.008] [Render thread/INFO] [Essential - Connection/]: Authenticating to Mojang as {MINECRAFT_USERNAME} ({MINECRAFT_UUID})
[18Oct2024 17:53:01.013] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.3.1 build 7
[18Oct2024 17:53:01.065] [ForkJoinPool.commonPool-worker-1/ERROR] [net.minecraftforge.eventbus.EventSubclassTransformer/EVENTBUS]: Could not find parent kotlin/jvm/internal/Lambda for class gg/essential/elementa/components/UIImage$2$1 in classloader jdk.internal.loader.ClassLoaders$AppClassLoader@6f496d9f on thread Thread[ForkJoinPool.commonPool-worker-1,5,main]
[18Oct2024 17:53:01.065] [ForkJoinPool.commonPool-worker-1/ERROR] [net.minecraftforge.eventbus.EventSubclassTransformer/EVENTBUS]: An error occurred building event handler
java.lang.ClassNotFoundException: kotlin.jvm.internal.Lambda
at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source) ~[?:?]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:97) ~[eventbus-6.0.5.jar:?]
at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:48) ~[eventbus-6.0.5.jar:?]
at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:26) ~[eventbus-6.0.5.jar:?]
at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:32) ~[eventbus-6.0.5.jar:6.0.5+6.0.5+master.eb8e549b]
at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?]
at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?]
at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?]
at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?]
at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?]
at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
at gg.essential.elementa.components.UIImage$2.invoke(UIImage.kt:61) ~[?:?]
at gg.essential.elementa.components.UIImage$2.invoke(UIImage.kt:46) ~[?:?]
at gg.essential.elementa.components.UIImage._init_$lambda$1(UIImage.kt:46) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source) ~[?:?]
at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
[18Oct2024 17:53:01.124] [DefaultDispatcher-worker-3/INFO] [Essential - Connection/]: Connecting to Essential Connection Manager...
[18Oct2024 17:53:01.149] [DefaultDispatcher-worker-3/INFO] [Essential Logger/]: Using Default JreDnsResolver... (518 KB left)

**Comment by NewJumper** [comment]
use the latest version of the mod

**Comment by AmbrusSynth** [comment]
Will the newest version work with mc 1.20.1?

**Comment by NewJumper** [comment]
yes
